---
# tasks file for roles/ec2

- name: Install pip
  ansible.builtin.apt:
    update_cache: yes
    name: python3-pip
    state: present

- name: Install boto
  pip:
    name:
      - botocore
      - boto3
    state: present

- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "atef-ansible-machine"
    key_name: "atef-key"
############# AWS Access Key ####################################
    vpc_subnet_id: subnet-0718d88ee525744d7
    instance_type: t3.small
    security_group: "atef-app-sg"
    region: us-east-1
    network_interfaces:
      - assign_public_ip: true
    image_id: ami-005fc0f236362e99f
    wait: yes
    tags:
      Environment: Ansible
  register: ec2

# - name: Show EC2 instance details
#   debug:
#     msg: "{{ ec2.instances }}"

- name: Show EC2 instance public IP
  debug:
    msg: "EC2 Instance Public IP: {{ ec2.instances[0].public_ip_address }}"

# - name: Add host to WordPress group
#   add_host:
#     hostname: "{{ ec2.instances[0].public_ip_address }}"

- name: Add EC2 IP to the hosts file
  lineinfile:
    create: yes
    path: /home/omar/ansible_practice/WordPress-Ansible/inventory/hosts
    line: "{{ ec2.instances[0].public_ip_address }}"

- name: Refresh inventory to include new hosts
  meta: refresh_inventory

- name: Pause until the machine is created
  pause:
    minutes: 1
